# Generated by Django 4.0.6 on 2022-07-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='curriculum',
            field=models.FileField(blank=True, null=True, upload_to='curriculuns_files'),
        ),
        migrations.AddField(
            model_name='account',
            name='github',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='portifolio',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='type_account',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Candidate', 'Candidate'), ('Hired', 'Hired'), ('Leader', 'Leader'), ('Recruiter', 'Recruiter')], default='Admin', max_length=50),
        ),
    ]
